# Generated by Django 5.0.4 on 2024-04-29 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_alter_user_email_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'this email already exists.'}, max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
