# Generated by Django 5.0.4 on 2024-05-16 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0003_remove_restaurant_comments_alter_restaurant_likes'),
        ('likeNcom_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='restaurant',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='food_app.restaurant'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
