# Generated by Django 5.0.4 on 2024-05-16 13:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0004_alter_restaurant_likes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='likes',
            field=models.ManyToManyField(blank=True, default='', related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
